In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('/content/Myocardial infarction complications.csv')

In [3]:
 data.tail()

,ID,AGE,SEX,INF_ANAM,STENOK_AN,FK_STENOK,IBS_POST,IBS_NASL,GB,SIM_GIPERT,...,JELUD_TAH,FIBR_JELUD,A_V_BLOK,OTEK_LANC,RAZRIV,DRESSLER,ZSN,REC_IM,P_IM_STEN,LET_IS
1695,1696,77.0,0,0.0,4.0,2.0,1.0,NaN,2.0,0.0,...,0,0,1,0,1,0,0,0,0,3
1696,1697,70.0,0,0.0,6.0,2.0,1.0,NaN,2.0,0.0,...,0,0,0,0,0,0,0,0,0,1
1697,1698,55.0,1,3.0,6.0,2.0,2.0,NaN,0.0,0.0,...,0,0,0,0,0,0,0,1,0,6
1698,1699,79.0,0,2.0,2.0,2.0,1.0,NaN,2.0,0.0,...,0,0,0,1,0,0,0,0,0,1
1699,1700,63.0,1,2.0,NaN,NaN,NaN,NaN,2.0,0.0,...,0,0,0,0,0,0,0,0,0,1

In [4]:
data.drop('ID', axis=1, inplace=True)

In [5]:
data

,AGE,SEX,INF_ANAM,STENOK_AN,FK_STENOK,IBS_POST,IBS_NASL,GB,SIM_GIPERT,DLIT_AG,...,JELUD_TAH,FIBR_JELUD,A_V_BLOK,OTEK_LANC,RAZRIV,DRESSLER,ZSN,REC_IM,P_IM_STEN,LET_IS
0,77.0,1,2.0,1.0,1.0,2.0,NaN,3.0,0.0,7.0,...,0,0,0,0,0,0,0,0,0,0
1,55.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,52.0,1,0.0,0.0,0.0,2.0,NaN,2.0,0.0,2.0,...,0,0,0,0,0,0,0,0,0,0
3,68.0,0,0.0,0.0,0.0,2.0,NaN,2.0,0.0,3.0,...,0,0,0,0,0,0,1,0,0,0
4,60.0,1,0.0,0.0,0.0,2.0,NaN,3.0,0.0,7.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1695,77.0,0,0.0,4.0,2.0,1.0,NaN,2.0,0.0,7.0,...,0,0,1,0,1,0,0,0,0,3
1696,70.0,0,0.0,6.0,2.0,1.0,NaN,2.0,0.0,7.0,...,0,0,0,0,0,0,0,0,0,1
1697,55.0,1,3.0,6.0,2.0,2.0,NaN,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,6
1698,79.0,0,2.0,2.0,2.0,1.0,NaN,2.0,0.0,7.0,...,0,0,0,1,0,0,0,0,0,1
1699,63.0,1,2.0,NaN,NaN,NaN,NaN,2.0,0.0,NaN,...,0,0,0,0,0,0,0,0,0,1

In [6]:
print(data.index)

RangeIndex(start=0, stop=1700, step=1)

In [11]:
x = data.loc[:,['AGE','SEX','RAZRIV','K_SH_POST','D_AD_ORIT','IBS_POST']]

In [12]:
x

       AGE  SEX  RAZRIV  K_SH_POST  D_AD_ORIT  IBS_POST
0     77.0    1       0        0.0      100.0       2.0
1     55.0    1       0        0.0       90.0       0.0
2     52.0    1       0        0.0      100.0       2.0
3     68.0    0       0        0.0       70.0       2.0
4     60.0    1       0        0.0       90.0       2.0
...    ...  ...     ...        ...        ...       ...
1695  77.0    0       1        0.0       70.0       1.0
1696  70.0    0       0        1.0        0.0       1.0
1697  55.0    1       0        NaN       50.0       2.0
1698  79.0    0       0        0.0       70.0       1.0
1699  63.0    1       0        1.0        0.0       NaN

[1700 rows x 6 columns]

In [13]:
x.columns

Index(['AGE', 'SEX', 'RAZRIV', 'K_SH_POST', 'D_AD_ORIT', 'IBS_POST'], dtype='object')

In [14]:
Y = data[['LET_IS']]

In [15]:
# identify columns with missing values
cols_with_missing = x.columns[x.isnull().any()]

# display columns with missing values
print(cols_with_missing)

Index(['AGE', 'K_SH_POST', 'D_AD_ORIT', 'IBS_POST'], dtype='object')

In [16]:
# fill in missing values with mode for each column
for col in cols_with_missing:
    mode_value = x[col].mode()[0]
    x[col] = x[col].fillna(mode_value)

In [17]:
x

       AGE  SEX  RAZRIV  K_SH_POST  D_AD_ORIT  IBS_POST
0     77.0    1       0        0.0      100.0       2.0
1     55.0    1       0        0.0       90.0       0.0
2     52.0    1       0        0.0      100.0       2.0
3     68.0    0       0        0.0       70.0       2.0
4     60.0    1       0        0.0       90.0       2.0
...    ...  ...     ...        ...        ...       ...
1695  77.0    0       1        0.0       70.0       1.0
1696  70.0    0       0        1.0        0.0       1.0
1697  55.0    1       0        0.0       50.0       2.0
1698  79.0    0       0        0.0       70.0       1.0
1699  63.0    1       0        1.0        0.0       2.0

[1700 rows x 6 columns]

In [18]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
import numpy as np
from imblearn.under_sampling import RandomUnderSampler

In [19]:
X_train,X_test,y_train,y_test = train_test_split(x,Y,test_size=0.2,random_state=50, stratify=Y)

In [20]:
# Initialize oversampler and undersampler
oversampler = SMOTE(random_state=42)
undersampler = RandomUnderSampler(random_state=42)

In [21]:
# Apply combination of oversampling and undersampling
X_train_resampled, y_train_resampled = oversampler.fit_resample(X_train, y_train)
X_train_resampled, y_train_resampled = undersampler.fit_resample(X_train_resampled, y_train_resampled)

In [22]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((1360, 6), (1360, 1), (340, 6), (340, 1))

Random Forest Classifier

In [23]:
# Initialize a Linear Regression model

from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [24]:
rf =  RandomForestClassifier()

In [25]:
from sklearn.model_selection import train_test_split, KFold, cross_val_score  # Import cross_val_score

 Initialize the KFold parameters

In [26]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

In [28]:
# Use cross_val_score on the model and dataset
scores = cross_val_score(rf, x, Y, cv=kfold, scoring='accuracy')

In [29]:
print("R2 scores for each fold:", scores)
print("Mean R2 score across all folds:", scores.mean())
mean_rf_score = scores.mean()

R2 scores for each fold: [0.88529412 0.86176471 0.9        0.86764706 0.84117647]
Mean R2 score across all folds: 0.8711764705882352

Decision Tree Classifier

In [30]:
from sklearn.tree import DecisionTreeClassifier

In [31]:
dc = DecisionTreeClassifier()

In [32]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

In [33]:
# Use cross_val_score on the model and dataset
scores = cross_val_score(dc, x, Y, cv=kfold, scoring='accuracy')

In [34]:
print("R2 scores for each fold:", scores)
print("Mean R2 score across all folds:", scores.mean())
mean_dc_score = scores.mean()

R2 scores for each fold: [0.85588235 0.84411765 0.88235294 0.85294118 0.79117647]
Mean R2 score across all folds: 0.8452941176470589

Logistic regression

In [35]:
lr = LogisticRegression()

In [36]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

In [37]:
# Use cross_val_score on the model and dataset
scores = cross_val_score(lr, x, Y, cv=kfold, scoring='accuracy')

In [38]:
print("R2 scores for each fold:", scores)
print("Mean R2 score across all folds:", scores.mean())
mean_lr_score = scores.mean()

R2 scores for each fold: [0.88823529 0.86470588 0.92647059 0.89705882 0.84117647]
Mean R2 score across all folds: 0.8835294117647059

In [39]:
model_df = pd.DataFrame({
    'Model': ['Random Forest', 'Decision Tree', 'Logistic Regression'],
    'Accuracy': [mean_rf_score,mean_dc_score,mean_lr_score]
})

In [40]:
model_df.sort_values(['Accuracy'],ascending=False,ignore_index=True)

                 Model  Accuracy
0  Logistic Regression  0.883529
1        Random Forest  0.871176
2        Decision Tree  0.845294

In [41]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import pickle

# Load your dataset and split it into features and labels
X = x
y = Y


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [42]:
# Save the trained model to a pickle file
with open('logistic_regression_model.pkl', 'wb') as file:
    pickle.dump(model, file)

In [43]:
# Load the trained model from the pickle file
with open('logistic_regression_model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

# Now you can use loaded_model for predictions